# Generated by Django 6.0.5 on 2026-05-31 04:30

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('action_type', models.CharField(choices=[('alert', '告警事件'), ('update_ticket', '更新单据信息')], max_length=32, verbose_name='事件类型')),
                ('config', jsonfield.fields.JSONField(default={}, help_text='类型详细配置', verbose_name='事件配置')),
            ],
            options={
                'verbose_name': '升级事件配置',
                'verbose_name_plural': '升级事件配置',
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=255, verbose_name='时间段名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '工作时间段',
                'verbose_name_plural': '工作时间段',
            },
        ),
        migrations.CreateModel(
            name='SlaTicketHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_timeout_color', models.CharField(max_length=32, verbose_name='预警单据背景色')),
                ('handle_timeout_color', models.CharField(max_length=32, verbose_name='超时单据背景色')),
            ],
        ),
        migrations.CreateModel(
            name='SlaTimerRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('service_type', models.CharField(max_length=64, verbose_name='服务类型')),
                ('name', models.CharField(default='', max_length=255, verbose_name='规则名称')),
                ('condition_type', models.CharField(choices=[('START', '开始'), ('STOP', '结束'), ('PAUSE', '暂停')], default='START', max_length=64, verbose_name='条件类型')),
                ('condition', jsonfield.fields.JSONField(default={}, verbose_name='条件')),
            ],
            options={
                'verbose_name': '计时规则',
                'verbose_name_plural': '计时规则',
            },
        ),
        migrations.CreateModel(
            name='ActionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=255, verbose_name='策略名称')),
                ('type', models.IntegerField(choices=[(1, '响应提醒'), (2, '响应超时'), (3, '处理提醒'), (4, '处理超时')], default=1, verbose_name='升级事件类型')),
                ('order', models.IntegerField(default=-1, verbose_name='策略顺序')),
                ('condition', jsonfield.fields.JSONField(help_text='当达到条件的时候，可以触发不同的动作', verbose_name='升级条件')),
                ('actions', models.ManyToManyField(help_text='处理事件', to='sla.action')),
            ],
            options={
                'verbose_name': '升级策略',
                'verbose_name_plural': '升级策略',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=255, verbose_name='假期名称')),
                ('day_of_week', models.CharField(default=-1, max_length=32, verbose_name='星期几')),
                ('type_of_day', models.CharField(choices=[('NORMAL', '常规日'), ('WORKDAY', '加班日'), ('HOLIDAY', '节假日')], default='NORMAL', max_length=32, verbose_name='日期类型')),
                ('start_date', models.DateField(null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(null=True, verbose_name='结束日期')),
                ('duration', models.ManyToManyField(help_text='工作时间段，没有配置的情况下，默认从0:00 -23:59', to='sla.duration')),
            ],
            options={
                'verbose_name': '工作日和节假日',
                'verbose_name_plural': '工作日和节假日',
            },
        ),
        migrations.CreateModel(
            name='PriorityMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('service_type', models.CharField(max_length=64, verbose_name='服务类型')),
                ('urgency', models.CharField(max_length=255, verbose_name='紧急程度')),
                ('impact', models.CharField(max_length=255, verbose_name='影响范围')),
                ('priority', models.CharField(blank=True, max_length=255, verbose_name='优先级')),
            ],
            options={
                'verbose_name': '优先级矩阵',
                'verbose_name_plural': '优先级矩阵',
                'unique_together': {('service_type', 'urgency', 'impact')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('is_enabled', models.BooleanField(default=True, help_text='是：启用当前工作日历配置， 否：默认采用7*24小时', verbose_name='配置是否生效')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('days', models.ManyToManyField(help_text='常规日历', related_name='days', to='sla.day')),
                ('holidays', models.ManyToManyField(default=None, help_text='假期', related_name='holidays', to='sla.day')),
                ('workdays', models.ManyToManyField(default=None, help_text='加班日', related_name='workdays', to='sla.day')),
            ],
            options={
                'verbose_name': '服务运营时间',
                'verbose_name_plural': '服务运营时间',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PriorityPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=255, verbose_name='策略名称')),
                ('priority', models.CharField(max_length=255, verbose_name='优先级')),
                ('handle_time', models.IntegerField(default=0, verbose_name='处理期限')),
                ('handle_unit', models.CharField(choices=[('m', '分钟'), ('h', '小时'), ('d', '天')], default='m', max_length=32, verbose_name='时长单位')),
                ('reply_time', models.IntegerField(blank=True, null=True, verbose_name='应答时长')),
                ('reply_unit', models.CharField(choices=[('m', '分钟'), ('h', '小时'), ('d', '天')], default='m', max_length=32, verbose_name='应答时长单位')),
                ('schedule', models.ForeignKey(help_text='服务时间', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='sla.schedule')),
            ],
            options={
                'verbose_name': '服务策略',
                'verbose_name_plural': '服务策略',
            },
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=255, verbose_name='Sla名称')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('is_reply_need', models.BooleanField(default=False, verbose_name='是否启用响应约定')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('action_policies', models.ManyToManyField(help_text='服务升级事件策略', related_name='a_slas', to='sla.actionpolicy')),
                ('policies', models.ManyToManyField(help_text='服务优先级策略', related_name='p_slas', to='sla.prioritypolicy')),
            ],
            options={
                'verbose_name': '服务协议',
                'verbose_name_plural': '服务协议',
                'ordering': ['-id'],
            },
        ),
    ]
