# Generated by Django 6.0.5 on 2026-06-01 09:10

import itsm.component.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_template', models.CharField(blank=True, default='', help_text='工单字段的值可以作为参数写到模板中，格式如：【ITSM】${service}管理单【${action}】提醒', max_length=255, null=True, verbose_name='标题模板')),
                ('content_template', models.TextField(blank=True, default='', help_text='工单字段的值可以作为参数写到模板中，格式如：单号:${sn}', null=True, verbose_name='内容模板')),
                ('action', models.CharField(choices=[('TERMINATE', '单据终止通知'), ('FOLLOW', '邀请关注通知'), ('INVITE', '邀请评价通知'), ('SUPERVISE', '单据督办通知'), ('SUSPEND', '单据挂起通知'), ('UNSUSPEND', '单据恢复通知'), ('TRANSITION', '单据待办通知'), ('WAITING_FOR_OPERATE', '任务待办通知'), ('WAITING_FOR_CONFIRM', '任务待总结通知'), ('NOTIFY_FOLLOWER', '关注人通知'), ('FINISHED', '单据结束通知'), ('SLA_HANDLE_WARNING_NOTIFY', 'SLA服务处理预警提醒通知'), ('SLA_HANDLE_OVERTIME_NOTIFY', 'SLA服务处理超时提醒通知'), ('SLA_REPLY_WARNING_NOTIFY', 'SLA服务响应预警提醒通知'), ('SLA_REPLY_OVERTIME_NOTIFY', 'SLA服务响应超时提醒'), ('NODE_FAILED', '节点失败通知')], default='default', max_length=32, verbose_name='通知模板类型')),
                ('notify_type', models.CharField(default='EMAIL', max_length=32, verbose_name='通知方式')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(default='system', max_length=64, verbose_name='更新人')),
                ('used_by', models.CharField(default='system', max_length=64, verbose_name='使用者')),
                ('version', models.CharField(default='V1', max_length=32, verbose_name='版本')),
                ('project_key', models.CharField(default='public', max_length=32, verbose_name='项目key')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, verbose_name='关键字')),
                ('value', itsm.component.fields.IOField(verbose_name='值')),
                ('type', models.CharField(choices=[('string', '字符串'), ('hash', '哈希值'), ('list', '列表'), ('set', '集合'), ('zset', '有序集合')], default='string', max_length=32, verbose_name='类型')),
                ('expire_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '数据存储',
                'verbose_name_plural': '数据存储',
            },
        ),
        migrations.CreateModel(
            name='MigrateLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_from', models.CharField(max_length=64, verbose_name='旧版本')),
                ('version_to', models.CharField(max_length=64, verbose_name='新版本')),
                ('operator', models.CharField(blank=True, max_length=64, verbose_name='升级人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('exe_func', models.JSONField(blank=True, default=list, verbose_name='执行的函数')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否执行结束')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否迁移成功')),
            ],
            options={
                'verbose_name': '数据迁移日志',
                'verbose_name_plural': '数据迁移日志',
            },
        ),
        migrations.CreateModel(
            name='ReleaseVersionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, verbose_name='版本号')),
                ('log', models.TextField(blank=True, default='', null=True, verbose_name='日志内容')),
                ('lang', models.CharField(default='zh-cn', max_length=64, verbose_name='语言')),
                ('create_at', models.DateField(verbose_name='日期')),
                ('is_latest', models.BooleanField(default=False, verbose_name='是否最新版本')),
                ('version_size', models.IntegerField(default=0, verbose_name='版本号大小')),
            ],
            options={
                'verbose_name': '版本日志',
                'verbose_name_plural': '版本日志',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('type', models.CharField(max_length=64, verbose_name='类型')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='关键字唯一标识')),
                ('value', models.TextField(blank=True, default='', null=True, verbose_name='系统设置值')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
