# Generated by Django 6.0.5 on 2026-05-31 04:30

import django.db.models.deletion
import pipeline.engine.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='节点 ID')),
                ('inputs', pipeline.engine.models.fields.IOField(default=None, verbose_name='输入数据')),
                ('outputs', pipeline.engine.models.fields.IOField(default=None, verbose_name='输出数据')),
                ('ex_data', pipeline.engine.models.fields.IOField(default=None, verbose_name='异常数据')),
            ],
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='对象唯一键')),
                ('obj', pipeline.engine.models.fields.IOField(verbose_name='对象存储字段')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='功能名称')),
                ('description', models.TextField(default='', verbose_name='功能描述')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', pipeline.engine.models.fields.IOField(default=None, verbose_name='输入数据')),
                ('outputs', pipeline.engine.models.fields.IOField(default=None, verbose_name='输出数据')),
                ('ex_data', pipeline.engine.models.fields.IOField(default=None, verbose_name='异常数据')),
            ],
        ),
        migrations.CreateModel(
            name='MultiCallbackData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('schedule_id', models.CharField(max_length=64, verbose_name='回调服务ID')),
                ('data', pipeline.engine.models.fields.IOField(verbose_name='回调数据')),
            ],
        ),
        migrations.CreateModel(
            name='NodeCeleryTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='节点 ID')),
                ('celery_task_id', models.CharField(default='', max_length=40, verbose_name='celery 任务 ID')),
            ],
        ),
        migrations.CreateModel(
            name='NodeRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor_id', models.CharField(db_index=True, max_length=32, verbose_name='祖先 ID')),
                ('descendant_id', models.CharField(db_index=True, max_length=32, verbose_name='后代 ID')),
                ('distance', models.IntegerField(db_index=True, verbose_name='距离')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineProcess',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Process ID')),
                ('root_pipeline_id', models.CharField(db_index=True, max_length=32, verbose_name='根 pipeline 的 ID')),
                ('current_node_id', models.CharField(db_index=True, default='', max_length=32, verbose_name='当前推进到的节点的 ID')),
                ('destination_id', models.CharField(default='', max_length=32, verbose_name='遇到该 ID 的节点就停止推进')),
                ('parent_id', models.CharField(default='', max_length=32, verbose_name='父 process 的 ID')),
                ('ack_num', models.IntegerField(default=0, verbose_name='收到子节点 ACK 的数量')),
                ('need_ack', models.IntegerField(default=-1, verbose_name='需要收到的子节点 ACK 的数量')),
                ('is_alive', models.BooleanField(db_index=True, default=True, verbose_name='该 process 是否还有效')),
                ('is_sleep', models.BooleanField(db_index=True, default=False, verbose_name='该 process 是否正在休眠')),
                ('is_frozen', models.BooleanField(db_index=True, default=False, verbose_name='该 process 是否被冻结')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessCeleryTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='pipeline 进程 ID')),
                ('celery_task_id', models.CharField(default='', max_length=40, verbose_name='celery 任务 ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('data', pipeline.engine.models.fields.IOField(verbose_name='pipeline 运行时数据')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleCeleryTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='schedule ID')),
                ('celery_task_id', models.CharField(default='', max_length=40, verbose_name='celery 任务 ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleService',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='ID 节点ID+version')),
                ('activity_id', models.CharField(db_index=True, max_length=32, verbose_name='节点 ID')),
                ('process_id', models.CharField(max_length=32, verbose_name='Pipeline 进程 ID')),
                ('schedule_times', models.IntegerField(default=0, verbose_name='被调度次数')),
                ('wait_callback', models.BooleanField(default=False, verbose_name='是否是回调型调度')),
                ('multi_callback_enabled', models.BooleanField(default=False, verbose_name='是否支持多次回调')),
                ('callback_data', pipeline.engine.models.fields.IOField(default=None, verbose_name='回调数据')),
                ('service_act', pipeline.engine.models.fields.IOField(verbose_name='待调度服务')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否已完成')),
                ('version', models.CharField(db_index=True, max_length=32, verbose_name='Activity 的版本')),
                ('is_scheduling', models.BooleanField(db_index=True, default=False, verbose_name='是否正在被调度')),
                ('last_schedule_time', models.DateTimeField(blank=True, null=True, verbose_name='最后调度时间')),
            ],
        ),
        migrations.CreateModel(
            name='SendFailedCeleryTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='任务名')),
                ('kwargs', models.TextField(verbose_name='任务参数')),
                ('type', models.IntegerField(choices=[(0, 'empty'), (1, 'process'), (2, 'node'), (3, 'schedule')], verbose_name='任务类型')),
                ('extra_kwargs', models.TextField(verbose_name='额外参数')),
                ('exec_trace', models.TextField(verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='节点 ID')),
                ('state', models.CharField(max_length=10, verbose_name='状态')),
                ('name', models.CharField(default='', max_length=64, verbose_name='节点名称')),
                ('retry', models.IntegerField(default=0, verbose_name='重试次数')),
                ('loop', models.IntegerField(default=1, verbose_name='循环次数')),
                ('skip', models.BooleanField(default=False, verbose_name='是否跳过')),
                ('error_ignorable', models.BooleanField(default=False, verbose_name='是否出错后自动忽略')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('started_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('archived_time', models.DateTimeField(null=True, verbose_name='归档时间')),
                ('version', models.CharField(max_length=32, verbose_name='版本')),
                ('state_refresh_at', models.DateTimeField(null=True, verbose_name='上次状态更新的时间')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='SubProcessRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('subprocess_id', models.CharField(db_index=True, max_length=32, verbose_name='子流程 ID')),
                ('process_id', models.CharField(max_length=32, verbose_name='对应的进程 ID')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=32, verbose_name='节点 id')),
                ('started_time', models.DateTimeField(verbose_name='开始时间')),
                ('archived_time', models.DateTimeField(verbose_name='结束时间')),
                ('loop', models.IntegerField(default=1, verbose_name='循环次数')),
                ('skip', models.BooleanField(default=False, verbose_name='是否跳过')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.historydata')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineModel',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='pipeline ID')),
                ('priority', models.IntegerField(default=100, verbose_name='流程优先级')),
                ('queue', models.CharField(default='', max_length=512, verbose_name='流程使用的队列名')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.pipelineprocess')),
            ],
        ),
        migrations.AddField(
            model_name='pipelineprocess',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.processsnapshot'),
        ),
    ]
