# Generated by Django 6.0.5 on 2026-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.IntegerField(db_index=True, default=0, verbose_name='任务ID')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], max_length=255, verbose_name='结果状态')),
                ('action_type', models.CharField(max_length=255, verbose_name='行为类型')),
                ('action_detail', models.JSONField(default=dict, verbose_name='行为详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='动作发生时间')),
                ('condition', models.JSONField(default=list, verbose_name='触发的规则')),
            ],
            options={
                'verbose_name': 'sla行为历史记录',
                'verbose_name_plural': 'sla行为历史记录',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='SlaEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_task_id', models.IntegerField(db_index=True, default=0, verbose_name='SLA TASK ID')),
                ('priority', models.CharField(max_length=255, verbose_name='优先级')),
                ('event_type', models.CharField(choices=[('PAUSE', '暂停'), ('RESUME', '恢复'), ('STOP', '停止'), ('START', '启动')], max_length=255, verbose_name='事件类型')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已归档')),
                ('tick_flag', models.CharField(choices=[('START', '开始计时'), ('END', '结束计时'), ('KEEP', '保持')], default='KEEP', max_length=255, verbose_name='计时标志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='事件发生时间')),
            ],
            options={
                'verbose_name': 'sla事件日志',
                'verbose_name_plural': 'sla事件日志',
            },
        ),
        migrations.CreateModel(
            name='SlaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_id', models.IntegerField(verbose_name='关联的sla协议ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='任务名称')),
                ('ticket_id', models.IntegerField(null=True, verbose_name='关联的单据ID')),
                ('start_node_id', models.IntegerField(null=True, verbose_name='计时开始节点ID')),
                ('end_node_id', models.IntegerField(null=True, verbose_name='计时结束节点ID')),
                ('deadline', models.DateTimeField(null=True, verbose_name='任务截止时间')),
                ('cost_time', models.IntegerField(default=0, verbose_name='经过的时长(s)')),
                ('begin_at', models.DateTimeField(null=True, verbose_name='任务开始计时的时间')),
                ('end_at', models.DateTimeField(null=True, verbose_name='任务结束计时的时间')),
                ('upgrade_at', models.DateTimeField(null=True, verbose_name='任务升级时间')),
                ('last_settlement_time', models.DateTimeField(null=True, verbose_name='上次结算时间')),
                ('sla_status', models.IntegerField(choices=[(1, '响应提醒'), (2, '响应超时'), (3, '处理提醒'), (4, '处理超时'), (5, '正常')], default=5, verbose_name='sla状态')),
                ('task_status', models.IntegerField(choices=[(1, '未激活'), (2, '计时中'), (3, '暂停中'), (4, '已停止')], default=1, verbose_name='任务状态')),
                ('is_reply_need', models.BooleanField(default=False, verbose_name='是否需要响应')),
                ('is_replied', models.BooleanField(default=False, verbose_name='是否已响应')),
                ('reply_deadline', models.DateTimeField(null=True, verbose_name='响应截至时间')),
                ('reply_cost', models.IntegerField(default=0, verbose_name='响应耗时(s)')),
                ('replied_at', models.DateTimeField(null=True, verbose_name='响应时间')),
            ],
            options={
                'verbose_name': 'sla任务',
                'verbose_name_plural': 'sla任务',
            },
        ),
    ]
