# Generated by Django 6.0.5 on 2026-05-31 04:30

import itsm.component.drf.mixins
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BKUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64, verbose_name='蓝鲸用户username')),
                ('roles', jsonfield.fields.JSONField(blank=True, default={'cmdb': {}, 'organization': []}, null=True, verbose_name='用户角色')),
                ('uid', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='用户uid')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '蓝鲸用户角色表',
                'verbose_name_plural': '蓝鲸用户角色表',
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('type', models.CharField(max_length=64, verbose_name='角色类型')),
                ('is_processor', models.BooleanField(default=True, verbose_name='可否操作单据')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': '用户角色类型',
                'verbose_name_plural': '用户角色类型',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('role_type', models.CharField(max_length=64, verbose_name='对应角色类型')),
                ('role_key', models.CharField(default='', max_length=128, verbose_name='角色唯一标识')),
                ('name', models.CharField(max_length=64, verbose_name='角色命名')),
                ('members', models.CharField(max_length=10000, verbose_name='角色组成人员')),
                ('owners', models.CharField(default='', max_length=10000, verbose_name='负责人')),
                ('access', models.CharField(max_length=128, verbose_name='对应服务')),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='用户角色描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
            ],
            options={
                'verbose_name': '用户角色和权限表',
                'verbose_name_plural': '用户角色和权限表',
            },
            bases=(itsm.component.drf.mixins.ObjectManagerMixin, models.Model),
        ),
    ]
