# Generated by Django 6.0.5 on 2026-06-01 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='角色组成人员'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_roles', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
