# Generated by Django 6.0.5 on 2026-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='members',
            field=models.TextField(default='', verbose_name='角色组成人员'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='owners',
            field=models.TextField(default='', verbose_name='负责人'),
        ),
    ]
