# Generated by Django 6.0.5 on 2026-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='变量编码')),
                ('status', models.BooleanField(default=True, verbose_name='变量是否可用')),
            ],
            options={
                'verbose_name': 'Variable变量',
                'verbose_name_plural': 'Variable变量',
            },
        ),
    ]
