# Generated by Django 6.0.5 on 2026-06-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('service_type', models.CharField(max_length=64, verbose_name='服务类型')),
                ('key', models.CharField(max_length=255, verbose_name='状态关键字')),
                ('name', models.CharField(max_length=255, verbose_name='状态名称')),
                ('color_hex', models.CharField(blank=True, max_length=32, verbose_name='二进制颜色')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='状态说明')),
                ('flow_status', models.CharField(choices=[('SUSPEND', '挂起中'), ('RUNNING', '执行中'), ('FINISHED', '成功结束'), ('FAILED', '失败结束'), ('TERMINATED', '撤销结束')], default='RUNNING', max_length=32, verbose_name='流程状态')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置状态')),
                ('is_start', models.BooleanField(default=False, verbose_name='是否为开始状态')),
                ('is_over', models.BooleanField(default=False, verbose_name='是否为结束状态')),
                ('is_suspend', models.BooleanField(default=False, verbose_name='是否为挂起状态')),
            ],
            options={
                'verbose_name': '工单状态',
                'verbose_name_plural': '工单状态',
            },
        ),
        migrations.CreateModel(
            name='TicketStatusConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('service_type', models.CharField(max_length=64, verbose_name='服务类型')),
                ('configured', models.BooleanField(default=False, verbose_name='已配置')),
            ],
            options={
                'verbose_name': '工单状态配置',
                'verbose_name_plural': '工单状态配置',
            },
        ),
        migrations.CreateModel(
            name='StatusTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('service_type', models.CharField(max_length=64, verbose_name='服务类型')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动转换')),
                ('threshold', models.IntegerField(default=0, verbose_name='阈值')),
                ('threshold_unit', models.CharField(choices=[('m', '分钟'), ('h', '小时'), ('d', '天')], default='m', max_length=32, verbose_name='时长单位')),
                ('from_status', models.ForeignKey(help_text='源状态', on_delete=django.db.models.deletion.CASCADE, related_name='from_transits', to='ticket_status.ticketstatus')),
                ('to_status', models.ForeignKey(help_text='目标状态', on_delete=django.db.models.deletion.CASCADE, related_name='to_transits', to='ticket_status.ticketstatus')),
            ],
            options={
                'verbose_name': '状态转换规则',
                'verbose_name_plural': '状态转换规则',
            },
        ),
    ]
