# Generated by Django 6.0.5 on 2026-05-31 04:30

import django.db.models.deletion
import itsm.component.drf.mixins
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=64, verbose_name='API名称')),
                ('path', models.CharField(max_length=1000, verbose_name='API路径')),
                ('version', models.CharField(max_length=32, null=True, verbose_name='API版本')),
                ('func_name', models.CharField(max_length=64, verbose_name='API调用函数')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=32, verbose_name='请求方法')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('owners', models.CharField(default='', max_length=10000, verbose_name='负责人')),
                ('req_headers', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='headers参数')),
                ('req_params', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='query参数')),
                ('req_body', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='body参数')),
                ('rsp_data', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='rsp_data')),
                ('before_req', models.TextField(default='', verbose_name='request预处理代码')),
                ('map_code', models.TextField(default='', verbose_name='response后处理代码')),
                ('is_activated', models.BooleanField(default=False, verbose_name='是否启用')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置API')),
                ('read_only', models.BooleanField(default=False, verbose_name='只读')),
            ],
            options={
                'verbose_name': '第三方API配置',
                'verbose_name_plural': '第三方API配置',
                'ordering': ('-create_at',),
            },
            bases=(itsm.component.drf.mixins.ObjectManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RemoteSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('system_id', models.IntegerField(default=0, verbose_name='系统id')),
                ('name', models.CharField(max_length=64, verbose_name='系统名称')),
                ('code', models.CharField(max_length=64, verbose_name='系统编码')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='系统描述')),
                ('owners', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='系统责任人')),
                ('contact_information', models.TextField(blank=True, verbose_name='联系方式')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置系统')),
                ('domain', models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='系统域名')),
                ('is_activated', models.BooleanField(default=False, verbose_name='是否启用')),
                ('headers', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='系统公共头部')),
                ('cookies', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='系统公共cookies')),
                ('variables', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='系统变量')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
            ],
            options={
                'verbose_name': '第三方系统配置',
                'verbose_name_plural': '第三方系统配置',
            },
        ),
        migrations.CreateModel(
            name='RemoteApiInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(default='', max_length=32, verbose_name='配置名称')),
                ('desc', models.CharField(default='', max_length=1000, null=True, verbose_name='配置描述')),
                ('req_params', jsonfield.fields.JSONField(default={}, verbose_name='query实例化参数')),
                ('req_body', jsonfield.fields.JSONField(default={}, verbose_name='body实例化参数')),
                ('rsp_data', models.CharField(default='', max_length=10000, verbose_name='返回参数')),
                ('succeed_conditions', jsonfield.fields.JSONField(default={}, verbose_name='成功条件')),
                ('end_conditions', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='结束条件（api节点可用）')),
                ('need_poll', models.BooleanField(default=False, verbose_name='是否轮询')),
                ('map_code', models.TextField(default='', verbose_name='response后处理代码')),
                ('before_req', models.TextField(default='', verbose_name='request预处理代码')),
                ('remote_api_info', jsonfield.fields.JSONField(default={}, verbose_name='remote_api_info')),
                ('remote_api', models.ForeignKey(help_text='api基础信息', on_delete=django.db.models.deletion.CASCADE, related_name='api_instances', to='postman.remoteapi')),
            ],
            options={
                'verbose_name': 'API配置参数实例',
                'verbose_name_plural': 'API配置参数实例',
            },
        ),
        migrations.AddField(
            model_name='remoteapi',
            name='remote_system',
            field=models.ForeignKey(help_text='对应的对接系统', on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='postman.remotesystem'),
        ),
    ]
