# Generated by Django 6.0.5 on 2026-06-01 09:10

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('ticket_id', models.IntegerField(default=0, verbose_name='单据ID')),
                ('state_id', models.IntegerField(default=0, verbose_name='节点ID')),
                ('activity_id', models.CharField(blank=True, max_length=64, verbose_name='Pipeline节点ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务的名称')),
                ('task_schema_id', models.IntegerField(verbose_name='对应的任务模板ID')),
                ('component_type', models.CharField(choices=[('NORMAL', '常规'), ('SOPS', '标准运维'), ('DEVOPS', '蓝盾')], max_length=64, verbose_name='任务组件类型')),
                ('processors_type', models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='处理人类型')),
                ('processors', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='处理人列表')),
                ('inputs', models.JSONField(default=dict, help_text='当前组件输入参数引用的参数变量', verbose_name='组件输入信息')),
                ('outputs', models.JSONField(default=dict, help_text='当前组件输出信息，比如sops各阶段返回', verbose_name='组件输出信息')),
                ('order', models.IntegerField(default=1, verbose_name='任务的执行顺序')),
                ('status', models.CharField(choices=[('NEW', '新建'), ('QUEUE', '待处理'), ('WAITING_FOR_OPERATE', '待处理'), ('WAITING_FOR_BACKEND', '后台处理中'), ('RUNNING', '执行中'), ('WAITING_FOR_CONFIRM', '待总结'), ('SKIPPED', '已忽略'), ('FAILED', '失败'), ('FINISHED', '完成'), ('REVOKED', '被撤销'), ('SUSPENDED', '被挂起'), ('DELETED', '被删除'), ('SUCCEED', '执行成功'), ('TERMINATE', '已终止'), ('CANCELED', '已取消')], default='NEW', max_length=64, verbose_name='任务的状态')),
                ('executor', models.CharField(default='', max_length=64, verbose_name='处理人')),
                ('confirmer', models.CharField(default='', max_length=64, verbose_name='确认人')),
                ('start_at', models.DateTimeField(null=True, verbose_name='开始执行的时间')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束执行的时间')),
                ('pipeline_data', models.JSONField(default=dict, verbose_name='Pipeline流程树元数据')),
                ('execute_state_id', models.IntegerField(default=0, verbose_name='执行节点ID')),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TaskLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('service_id', models.IntegerField(verbose_name='服务ID')),
                ('name', models.CharField(max_length=64, verbose_name='任务库名称')),
            ],
            options={
                'verbose_name': '任务库',
                'verbose_name_plural': '任务库',
                'ordering': ('-id',),
            },
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否是内置字段')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='是否只读')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否生效')),
                ('display', models.BooleanField(default=False, verbose_name='是否显示在单据列表中')),
                ('source_type', models.CharField(choices=[('CUSTOM', '自定义数据'), ('API', '接口数据'), ('DATADICT', '数据字典'), ('RPC', '系统数据'), ('CUSTOM_API', '自定义API')], default='CUSTOM', max_length=32, verbose_name='数据来源类型')),
                ('source_uri', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='接口uri')),
                ('api_instance_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='api实例主键')),
                ('kv_relation', models.JSONField(default=dict, verbose_name='源数据的kv关系配置')),
                ('type', models.CharField(choices=[('STRING', '单行文本'), ('TEXT', '多行文本'), ('INT', '数字'), ('DATE', '日期'), ('DATETIME', '日期时间'), ('DATETIMERANGE', '时间间隔'), ('TABLE', '表格'), ('SELECT', '单选下拉框'), ('INPUTSELECT', '可输入单选下拉框'), ('MULTISELECT', '多选下拉框'), ('CHECKBOX', '复选框'), ('RADIO', '单选框'), ('MEMBER', '单个人员选择'), ('MEMBERS', '多个人员选择'), ('RICHTEXT', '富文本'), ('FILE', '附件上传'), ('CUSTOMTABLE', '自定义表格'), ('TREESELECT', '树形选择'), ('LINK', '链接'), ('CUSTOM-FORM', '自定义表单'), ('CASCADE', '级联')], default='STRING', max_length=32, verbose_name='字段类型')),
                ('key', models.CharField(max_length=255, verbose_name='字段标识')),
                ('name', models.CharField(max_length=64, verbose_name='字段名')),
                ('layout', models.CharField(choices=[('COL_6', '半行'), ('COL_12', '整行')], default='COL_6', max_length=32, verbose_name='布局')),
                ('validate_type', models.CharField(choices=[('OPTION', '可选'), ('REQUIRE', '必填')], default='REQUIRE', max_length=32, verbose_name='校验规则')),
                ('show_type', models.IntegerField(choices=[(1, '直接显示'), (0, '根据条件判断')], default=1, verbose_name='显示条件类型')),
                ('show_conditions', models.JSONField(default=dict, verbose_name='字段的显示条件')),
                ('regex', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='正则校验规则关键字')),
                ('regex_config', models.JSONField(default=dict, verbose_name='正则校验规则配置')),
                ('custom_regex', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='自定义正则规则')),
                ('desc', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='字段填写说明')),
                ('tips', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='字段展示说明')),
                ('is_tips', models.BooleanField(default=False, verbose_name='额外提示')),
                ('default', models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='默认值')),
                ('choice', models.JSONField(default=list, verbose_name='选项')),
                ('related_fields', models.JSONField(blank=True, default=dict, null=True, verbose_name='级联字段')),
                ('meta', models.JSONField(default=dict, verbose_name='复杂描述信息')),
                ('stage', models.CharField(choices=[('CREATE', '新建'), ('OPERATE', '处理'), ('CONFIRM', '确认')], default='CREATE', max_length=64, verbose_name='所处阶段')),
                ('sequence', models.IntegerField(default=0, verbose_name='序号')),
                ('_value', models.TextField(blank=True, null=True, verbose_name='表单值')),
                ('task', models.ForeignKey(help_text='对应的任务模型', on_delete=django.db.models.deletion.CASCADE, related_name='all_fields', to='task.task')),
            ],
            options={
                'verbose_name': '任务字段表',
                'verbose_name_plural': '任务字段表',
                'ordering': ('-id',),
            },
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskLibTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=64, verbose_name='任务名称')),
                ('task_schema_id', models.CharField(max_length=64, verbose_name='任务模版ID')),
                ('component_type', models.CharField(max_length=64, verbose_name='任务类型')),
                ('processors_type', models.CharField(max_length=64, verbose_name='处理人类型')),
                ('processors', models.CharField(max_length=255, verbose_name='处理人')),
                ('fields', models.JSONField(default=list, verbose_name='字段列表')),
                ('sub_template_id', models.CharField(default='', max_length=64, verbose_name='子模版ID')),
                ('project_id', models.CharField(default='', max_length=64, verbose_name='项目ID/业务ID')),
                ('exclude_task_nodes', models.JSONField(default=list, verbose_name='排除节点ID列表')),
                ('task_lib', models.ForeignKey(help_text='关联的任务库', on_delete=django.db.models.deletion.CASCADE, related_name='lib_tasks', to='task.tasklib')),
            ],
            options={
                'verbose_name': '任务库任务列表',
                'verbose_name_plural': '任务库任务列表',
            },
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
