# Generated by Django 6.0.5 on 2026-06-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='processors_type',
            field=models.CharField(choices=[('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='处理人类型'),
        ),
    ]
