# Generated by Django 6.0.5 on 2026-05-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.SlugField(max_length=128, verbose_name='logger 名称')),
                ('level_name', models.SlugField(max_length=32, verbose_name='日志等级')),
                ('message', models.TextField(null=True, verbose_name='日志内容')),
                ('exception', models.TextField(null=True, verbose_name='异常信息')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='输出时间')),
                ('node_id', models.CharField(db_index=True, max_length=32, verbose_name='节点 ID')),
                ('history_id', models.IntegerField(default=-1, verbose_name='节点执行历史 ID')),
            ],
        ),
    ]
