# -*- coding: utf-8 -*-
"""监控配置"""
import os

MONITOR_PROXY_IP = os.getenv("MONITOR_PROXY_IP", "")
MONITOR_PROXY_PORT = os.getenv("MONITOR_PROXY_PORT", "10205")
MONITOR_EVENT_DATA_ID = os.getenv("MONITOR_EVENT_DATA_ID", "")
MONITOR_EVENT_TOKEN = os.getenv("MONITOR_EVENT_TOKEN", "")
IS_MONITOR_EVENT = os.getenv("IS_MONITOR_EVENT", False)
AUTO_TIMEOUT_MINUTES = os.getenv("AUTO_TIMEOUT_MINUTES", 30)

AUTOSTATE_SCHEDULE_INTERVAL = os.getenv("AUTOSTATE_SCHEDULE_INTERVAL", 30)
TAM_PROJECT_ID = os.environ.get("TAM_PROJECT_ID", "")

STATSD_HOST = os.environ.get("STATSD_HOST", "localhost")
STATSD_PORT = os.environ.get("STATSD_PORT", 8125)
STATSD_PREFIX = os.environ.get("STATSD_PREFIX", None)
