# Generated by Django 6.0.5 on 2026-05-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='项目唯一标识')),
                ('name', models.CharField(max_length=128, verbose_name='项目名')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='项目描述')),
                ('logo', models.TextField(blank=True, default='', verbose_name='logo base64 内容')),
                ('color', models.CharField(default='', max_length=32, null=True, verbose_name='项目颜色')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProjectAccessRecord',
            fields=[
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户名')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('type', models.CharField(default='FUNCTION', max_length=64, verbose_name='类型')),
                ('key', models.CharField(max_length=64, verbose_name='关键字唯一标识')),
                ('value', models.TextField(blank=True, default='', null=True, verbose_name='系统设置值')),
                ('project', models.ForeignKey(help_text='项目', on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
