# Generated by Django 6.0.5 on 2026-06-04 09:27

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='格式: {type}:{module}:{action}，如 feature:system:user-manage', max_length=128, unique=True, verbose_name='权限编码')),
                ('name', models.CharField(max_length=255, verbose_name='权限名称')),
                ('category', models.CharField(choices=[('workflow', '流程管理'), ('ticket', '工单管理'), ('service', '服务管理'), ('sla', 'SLA 管理'), ('system', '系统管理'), ('project', '项目管理'), ('task', '任务管理')], max_length=64, verbose_name='业务分类')),
                ('permission_type', models.CharField(choices=[('page', '页面'), ('button', '按钮'), ('feature', '功能')], max_length=16, verbose_name='权限类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'users_permission',
                'ordering': ['category', 'permission_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='如 password_min_length', max_length=128, unique=True, verbose_name='策略键')),
                ('value', models.JSONField(help_text='JSON 格式，支持 int/bool/str', verbose_name='策略值')),
                ('category', models.CharField(choices=[('password', '密码策略'), ('login', '登录策略'), ('session', '会话策略')], max_length=32, verbose_name='策略分类')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=True, verbose_name='内置策略')),
            ],
            options={
                'verbose_name': '安全策略',
                'verbose_name_plural': '安全策略',
                'db_table': 'users_security_policy',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'users_department',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, default='', max_length=255, verbose_name='昵称')),
                ('chname', models.CharField(blank=True, default='', max_length=255, verbose_name='中文名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='电话')),
                ('is_staff', models.BooleanField(default=False, verbose_name='后台访问权限')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('leader', models.ForeignKey(blank=True, help_text='用户的直属上级，用于工单 STARTER_LEADER / ASSIGN_LEADER 处理人解析', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='直属上级')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, help_text='用户的主要所属部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='users.department', verbose_name='主部门')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128, verbose_name='用户名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('attempts', models.IntegerField(default=0, verbose_name='失败次数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定至')),
            ],
            options={
                'verbose_name': '登录尝试',
                'verbose_name_plural': '登录尝试',
                'db_table': 'users_login_attempt',
                'unique_together': {('username', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '密码历史',
                'verbose_name_plural': '密码历史',
                'db_table': 'users_password_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='角色名称')),
                ('role_key', models.CharField(help_text='唯一标识，如 SUPERUSER', max_length=128, unique=True, verbose_name='角色标识')),
                ('desc', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置角色')),
                ('creator', models.CharField(blank=True, default='', max_length=128, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=128, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('members', models.ManyToManyField(blank=True, related_name='auth_roles', to=settings.AUTH_USER_MODEL, verbose_name='角色成员')),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_auth_roles', to=settings.AUTH_USER_MODEL, verbose_name='角色负责人')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='权限列表')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='角色组名称')),
                ('group_key', models.CharField(help_text='唯一标识，如 DEV, OPS', max_length=128, unique=True, verbose_name='角色组标识')),
                ('desc', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置角色组')),
                ('project_key', models.CharField(default='0', help_text="默认 '0' 表示全局", max_length=64, verbose_name='项目标识')),
                ('creator', models.CharField(blank=True, default='', max_length=128, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='', max_length=128, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('members', models.ManyToManyField(blank=True, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='组成员')),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_user_groups', to=settings.AUTH_USER_MODEL, verbose_name='组负责人')),
            ],
            options={
                'verbose_name': '角色组',
                'verbose_name_plural': '角色组',
                'db_table': 'users_user_group',
            },
        ),
        migrations.CreateModel(
            name='DeptMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主部门')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_memberships', to='users.department', verbose_name='部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '部门成员',
                'verbose_name_plural': '部门成员',
                'db_table': 'users_dept_membership',
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='属性键')),
                ('value', models.TextField(blank=True, default='', verbose_name='属性值')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户属性',
                'verbose_name_plural': '用户属性',
                'db_table': 'users_user_property',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
