# Generated by Django 6.0.5 on 2026-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='组件编码')),
                ('version', models.CharField(default='legacy', max_length=64, verbose_name='组件版本')),
                ('name', models.CharField(max_length=255, verbose_name='组件名称')),
                ('status', models.BooleanField(default=True, verbose_name='组件是否可用')),
            ],
            options={
                'verbose_name': '组件 Component',
                'verbose_name_plural': '组件 Component',
                'ordering': ['-id'],
            },
        ),
    ]
