# Generated by Django 6.0.5 on 2026-06-01 09:13

import django.db.models.deletion
import django.db.models.manager
import itsm.component.drf.mixins
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('order', models.IntegerField(default=1, verbose_name='service序列')),
            ],
            options={
                'verbose_name': '服务分类表',
                'verbose_name_plural': '服务分类表',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='收藏名称')),
                ('service', models.CharField(max_length=64, verbose_name='服务类型')),
                ('data', models.JSONField(default=list, verbose_name='收藏数据')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='FavoriteService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='收藏的用户')),
                ('service_id', models.IntegerField(verbose_name='服务标识')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('key', models.CharField(default='DEFAULT', max_length=64, verbose_name='服务编号')),
                ('name', models.CharField(max_length=255, verbose_name='服务名称')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='服务描述')),
                ('owners', models.TextField(default='admin', help_text='服务负责人')),
                ('can_ticket_agency', models.BooleanField(default=False, verbose_name='是否可以代提单')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('display_type', models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('ORGANIZATION', '组织架构'), ('INVISIBLE', '不可见'), ('API', '第三方系统')], default='OPEN', max_length=32, verbose_name='可见范围类型')),
                ('display_role', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='可见范围')),
                ('source', models.CharField(choices=[('custom', '自定义'), ('service', '服务'), ('template', '模版')], default=None, max_length=32, null=True, verbose_name='来源')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
            bases=(itsm.component.drf.mixins.ObjectManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, default='system', max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='system', max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='目录关键字')),
                ('name', models.CharField(max_length=64, verbose_name='目录名称')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='目录描述')),
                ('order', models.IntegerField(default=1, verbose_name='节点顺序')),
                ('xt_only', models.BooleanField(default=False, verbose_name='特殊过滤')),
                ('route', models.JSONField(default=list, verbose_name='前置路径集合')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': '服务目录',
                'verbose_name_plural': '服务目录',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='关键字')),
                ('name', models.CharField(default='', max_length=255, verbose_name='服务名称')),
                ('desc', models.CharField(max_length=255, verbose_name='服务描述')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
            },
        ),
        migrations.CreateModel(
            name='ServiceSla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='服务ID')),
                ('start_node_id', models.IntegerField(verbose_name='计时开始节点ID')),
                ('end_node_id', models.IntegerField(verbose_name='计时结束节点ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('sla_id', models.IntegerField(verbose_name='SLA协议 ID')),
                ('color', models.CharField(default='', max_length=32, verbose_name='颜色标志')),
                ('lines', models.JSONField(default=list, verbose_name='线条列表')),
                ('states', models.JSONField(default=list, verbose_name='节点列表')),
            ],
            options={
                'verbose_name': '服务与SLA关联表',
                'verbose_name_plural': '服务与SLA关联表',
            },
        ),
        migrations.CreateModel(
            name='SysDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('end_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('project_key', models.CharField(default=0, max_length=32, verbose_name='项目key')),
                ('key', models.CharField(max_length=255, verbose_name='编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('desc', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='描述')),
                ('owners', models.CharField(default='', max_length=10000, verbose_name='负责人')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='是否只读')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '数据字典',
                'verbose_name_plural': '数据字典',
            },
            bases=(itsm.component.drf.mixins.ObjectManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, default='system', max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, default='system', max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('key', models.CharField(max_length=255, verbose_name='编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='是否只读（不可编辑）')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置（不可删除）')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='service.dictdata', verbose_name='上级目录')),
            ],
            options={
                'verbose_name': '字典数据',
                'verbose_name_plural': '字典数据',
                'ordering': ('order',),
            },
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
