# Generated by Django 6.0.5 on 2026-06-01 09:13

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(help_text='收藏的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='workflow',
            field=models.ForeignKey(help_text='关联流程版本', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workflow.workflowversion'),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='service',
            field=models.ForeignKey(help_text='关联服务条目', on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='service.servicecatalog', verbose_name='上级目录'),
        ),
        migrations.AddField(
            model_name='catalogservice',
            name='catalog',
            field=models.ForeignKey(help_text='关联服务目录', on_delete=django.db.models.deletion.CASCADE, to='service.servicecatalog'),
        ),
        migrations.AddField(
            model_name='dictdata',
            name='dict_table',
            field=models.ForeignKey(help_text='关联字典项', on_delete=django.db.models.deletion.CASCADE, related_name='dict_data', to='service.sysdict'),
        ),
        migrations.AlterUniqueTogether(
            name='dictdata',
            unique_together={('dict_table', 'key')},
        ),
    ]
